---
title: Senshu
baseurl: /senshu

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  pentcoms:
    output: true

defaults:
  - scope:
      path: '_pentcoms'
    values:
      layout: bin
